name: Build TypeScript Project

on:
  push:
    paths: 
      - "**/*.ts"
      - "websocket/frontend/*"
      - ".github/workflows/js.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: websocket/frontend
      run: npm install

    - name: Lint
      working-directory: websocket/frontend
      run: npm run lint

    - name: Build project
      working-directory: websocket/frontend
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "websocket/frontend/html/"
        retention-days: 1

  push:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4